[pytest]
addopts = -v -s --alluredir=final_work/tests/allure_results
testpaths = final_work/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
selenium_url = http://127.0.0.1:4444/wd/hub
browser_name = chrome
browser_version = 125.0
headless = False