name: skillbox_7
channels:
  - conda-forge
dependencies:
  - python=3.11
  - requests
  - selenium=4.10
  - webdriver-manager
  - pytest
  - pip:
      - allure-pytest
      - flake8
      - pytest-playwright
